language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua

after_success:
  - bash <(curl -s https://codecov.io/bash)

ignore:
  - module-info.java

dist: trusty

notifications:
  email:
    recipients:
      - asayos@fi.uba.ar
    on_failure: always

